apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  namespace: ingress-nginx
  labels:
    app: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go
          image: jang1023/shinhan:f2e8fc38d0db6ab22c6fa8f7959128b8ecb648fb
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: ingress-nginx
spec:
  selector:
    app: go
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
